import asyncio
from playwright.async_api import async_playwright

async def run():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        # Create a new context so we can record video
        context = await browser.new_context(record_video_dir="./videos/")
        page = await context.new_page()

        # Handle console to debug
        page.on("console", lambda msg: print(f"PAGE LOG: {msg.text}"))

        # The actual request path generated by Supabase client
        # In this project, Supabase uses https://jidogpcnjnilotkdptzd.supabase.co
        async def mock_supabase(route):
            await asyncio.sleep(2.0) # simulate network delay
            await route.continue_()

        await page.route("https://jidogpcnjnilotkdptzd.supabase.co/**", mock_supabase)

        # Go to Dashboard
        await page.goto('http://localhost:8000/dashboard.html')
        await page.wait_for_selector('text=Admin Login')

        # Verify Email Label
        email_input = page.locator('input#email').first
        assert await email_input.get_attribute('aria-label') == 'Email', "aria-label should be Email"

        # Fill form
        await email_input.fill('test@example.com')
        await page.fill('input#password', 'password123')

        # Verify loading state on submit
        submit_btn = page.locator('button#login-submit')

        # Click without awaiting navigation so we can assert the UI state immediately
        click_task = asyncio.create_task(submit_btn.click())

        # Wait a small bit for UI to update
        await asyncio.sleep(0.5)

        # Capture screenshot while loading
        await page.screenshot(path='./a11y_loading_state.png')

        is_disabled = await submit_btn.evaluate("el => el.disabled")
        text = await submit_btn.evaluate("el => el.textContent")

        # Wait for the request to complete
        await click_task

        assert is_disabled, "Button should be disabled during submit"
        assert text == "Signing in...", "Button text should be 'Signing in...' during submit"

        await context.close()
        await browser.close()

asyncio.run(run())
